// Decoding, against bytes the server actually sent.
//
// These fixtures are bytes the server sent, captured by
// `scripts/capture-companion-fixtures.mjs` against a harness started on a
// temporary HOME. That matters more than it sounds: hand-written test JSON
// tests our idea of the API, and the whole risk in a two-language client is
// that our idea drifts from the API without anything failing. When a server
// payload changes, re-capturing makes these fail, which is the alarm.
//
// One exception, and it is marked in the script: options-card.json needs a
// bot to actually ask for approval, which needs a real provider and a real
// turn, so it is not regenerated by a run.
import XCTest
@testable import CompanionCore

final class DecodingTests: XCTestCase {
    // MARK: - Fixtures

    func fixture(_ name: String) throws -> Data {
        guard let url = Bundle.module.url(forResource: name, withExtension: "json", subdirectory: "Fixtures")
            ?? Bundle.module.url(forResource: name, withExtension: "json")
        else {
            XCTFail("missing fixture \(name).json — run scripts/capture-companion-fixtures.mjs")
            throw CocoaError(.fileNoSuchFile)
        }
        return try Data(contentsOf: url)
    }

    func decode<T: Decodable>(_ type: T.Type, _ name: String) throws -> T {
        try JSONDecoder().decode(type, from: try fixture(name))
    }

    // MARK: - Hydration

    func testRoutineExecutionMarkerIsOptionalAndPreserved() throws {
        let legacy = try JSONDecoder().decode(
            BotTask.self, from: Data(#"{"threadId":"legacy","title":"Legacy","createdAt":1}"#.utf8)
        )
        let execution = try JSONDecoder().decode(
            BotTask.self, from: Data(#"{"threadId":"run-thread","title":"Brief","createdAt":2,"routineRunId":"run-1"}"#.utf8)
        )
        XCTAssertNil(legacy.routineRunId)
        XCTAssertEqual(execution.routineRunId, "run-1")
        XCTAssertEqual(try JSONDecoder().decode(BotTask.self, from: JSONEncoder().encode(execution)), execution)
    }

    func testDecodesThePagedFleet() throws {
        let fleet = try decode(Fleet.self, "bots-paged")
        XCTAssertFalse(fleet.bots.isEmpty)

        let bot = try XCTUnwrap(fleet.bots.first)
        XCTAssertFalse(bot.id.isEmpty)
        XCTAssertFalse(bot.threadId.isEmpty)
        XCTAssertFalse(bot.name.isEmpty)
        XCTAssertNotNil(bot.messages)

        // the paged shape caps each thread and says whether there is more
        let room = try XCTUnwrap(fleet.groups.first)
        XCTAssertEqual(room.messages?.count, 3)
        XCTAssertEqual(room.hasMore, true)
    }

    func testDecodesTheFullFleetToo() throws {
        // omitting ?messages must stay decodable by the same types — it is
        // what the desktop gets, and what a phone falls back to
        let fleet = try decode(Fleet.self, "bots-full")
        XCTAssertFalse(fleet.bots.isEmpty)
        XCTAssertNil(fleet.bots.first?.hasMore)
    }

    func testDecodesABotOverview() throws {
        let overview = try decode(BotOverview.self, "bot-overview")
        XCTAssertEqual(overview.who.name, "Kiwi")
        XCTAssertEqual(overview.who.soulLead, "File bugs.")
        XCTAssertFalse(overview.does.isEmpty)
        XCTAssertFalse(overview.wont.isEmpty)
        XCTAssertFalse(overview.recent.isEmpty)
    }

    func testStorePreviewRemainsADecodableFleet() throws {
        let iosDirectory = URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()
            .deletingLastPathComponent()
            .deletingLastPathComponent()
        let data = try Data(contentsOf: iosDirectory.appendingPathComponent("App/StorePreview.json"))
        let fleet = try JSONDecoder().decode(Fleet.self, from: data)

        XCTAssertFalse(fleet.bots.isEmpty)
        XCTAssertFalse(fleet.groups.isEmpty)
    }

    func testOldAndNewAvatarProfilesDecodeTogether() throws {
        let oldBot = try XCTUnwrap(decode(Fleet.self, "bots-full").bots.first)
        XCTAssertNil(oldBot.avatarUrl)
        XCTAssertNil(oldBot.avatarCrop)

        let newBot = try XCTUnwrap(decode(Fleet.self, "bot-avatar-profile").bots.first)
        XCTAssertEqual(newBot.avatarUrl, "/api/attachments/123e4567-e89b-12d3-a456-426614174000.webp")
        XCTAssertEqual(newBot.avatarCrop, .rounded)
        XCTAssertEqual(newBot.voice, "voice-1")
        XCTAssertEqual(newBot.speakReplies, true)
    }

    func testFutureAvatarCropFallsBackWithoutDroppingTheBot() throws {
        let fixture = String(decoding: try fixture("bot-avatar-profile"), as: UTF8.self)
            .replacingOccurrences(of: #""avatarCrop":"rounded""#, with: #""avatarCrop":"hexagon""#)
        let fleet = try JSONDecoder().decode(Fleet.self, from: Data(fixture.utf8))

        XCTAssertEqual(fleet.bots.count, 1)
        XCTAssertEqual(fleet.bots.first?.avatarCrop, .mascot)
    }

    func testFutureRoutineScheduleKindRemainsVisibleAsUnknown() throws {
        let schedule = try JSONDecoder().decode(
            RoutineSchedule.self,
            from: Data(#"{"type":"weekly","time":"09:00","weekdays":[1]}"#.utf8)
        )

        XCTAssertEqual(schedule.type, .unknown)
        XCTAssertEqual(schedule.time, "09:00")
        XCTAssertEqual(schedule.weekdays, [1])
    }

    func testDecodesAnIntervalRoutineSchedule() throws {
        let schedule = try JSONDecoder().decode(
            RoutineSchedule.self,
            from: Data(#"{"type":"interval","everyMinutes":5,"anchorAt":1788384600000}"#.utf8)
        )

        XCTAssertEqual(schedule.type, .interval)
        XCTAssertEqual(schedule.everyMinutes, 5)
        XCTAssertEqual(schedule.anchorAt, 1_788_384_600_000)
        XCTAssertNil(schedule.at)
        XCTAssertNil(schedule.time)
        XCTAssertNil(schedule.weekdays)
    }

    func testNotificationTargetRequiresBothExactIds() {
        XCTAssertEqual(
            NotificationTarget(payload: ["botId": "bot-1", "threadId": "detached-task-2"]),
            NotificationTarget(botId: "bot-1", threadId: "detached-task-2")
        )
        XCTAssertNil(NotificationTarget(payload: ["botId": "bot-1"]))
        XCTAssertNil(NotificationTarget(payload: ["threadId": "task-1"]))
        XCTAssertNil(NotificationTarget(botId: " ", threadId: "task-1"))
        guard let detached = NotificationTarget(botId: "bot-1", threadId: "task-2") else {
            return XCTFail("valid notification target")
        }
        XCTAssertTrue(detached.requiresTaskSwitch(activeThreadId: "task-1"))
        XCTAssertFalse(detached.requiresTaskSwitch(activeThreadId: "task-2"))
    }

    func testDecodesTheCloudBackendAndItsAbsence() throws {
        // The cloud-desktop button hides on cloudBackend == "vps", so both
        // sides of that gate must decode: a harness that sends the field, and
        // an older one that has never heard of it (nil keeps the button).
        let json = """
        {
          "bots": [
            {
              "id":"b1","threadId":"t1","name":"Scout","title":"","description":"",
              "notifications":true,"color":"green","unread":false,
              "modelSelection":{"instanceId":"i1","model":"m1"},"createdAt":1,
              "computer":"cloud","cloudBackend":"vps"
            },
            {
              "id":"b2","threadId":"t2","name":"Rio","title":"","description":"",
              "notifications":true,"color":"blue","unread":false,
              "modelSelection":{"instanceId":"i1","model":"m1"},"createdAt":2,
              "computer":"cloud"
            }
          ],
          "groups": []
        }
        """
        let fleet = try JSONDecoder().decode(Fleet.self, from: Data(json.utf8))
        XCTAssertEqual(fleet.bots.first?.cloudBackend, "vps")
        XCTAssertNil(fleet.bots.last?.cloudBackend)
    }

    func testDecodesSidebarSectionsOnBotsAndChannels() throws {
        let json = """
        {
          "bots": [
            {
              "id":"b1","threadId":"t1","name":"Scout","title":"","description":"",
              "notifications":true,"color":"green","unread":false,"section":"Research",
              "modelSelection":{"instanceId":"i1","model":"m1"},"createdAt":1
            }
          ],
          "groups": [
            {
              "id":"g1","threadId":"gt1","name":"Launch","memberIds":["b1"],
              "defaultResponder":{"kind":"mentions"},"bulletin":"","unread":false,
              "createdAt":2,"section":"Research"
            }
          ]
        }
        """
        let fleet = try JSONDecoder().decode(Fleet.self, from: Data(json.utf8))

        XCTAssertEqual(fleet.bots.first?.section, "Research")
        XCTAssertEqual(fleet.groups.first?.section, "Research")
        XCTAssertNil(try decode(Fleet.self, "bots-full").bots.first?.section,
                     "older computers that omit sections remain compatible")
    }

    func testDecodesMultipleConnectedAccountsAndNoAuthToolkit() throws {
        let payload = #"""
        {
          "configured": true,
          "services": {
            "gmail": {
              "connected": true,
              "pending": false,
              "status": "ACTIVE",
              "accounts": [
                {"id": "ca_work", "alias": "Work", "status": "ACTIVE"},
                {"id": "ca_personal", "status": "INACTIVE"}
              ]
            },
            "weather": {
              "connected": true,
              "pending": false,
              "status": "ACTIVE",
              "accounts": []
            },
            "slack": {
              "connected": false,
              "pending": true
            }
          }
        }
        """#
        let statuses = try JSONDecoder().decode(ConnectorStatuses.self, from: Data(payload.utf8))
        let gmail = try XCTUnwrap(statuses.services["gmail"])
        XCTAssertEqual(gmail.accounts?.map(\.id), ["ca_work", "ca_personal"])
        XCTAssertEqual(gmail.accounts?.first?.alias, "Work")
        XCTAssertNil(gmail.accounts?.last?.alias)
        XCTAssertTrue(try XCTUnwrap(gmail.accounts?.first).isActive)
        XCTAssertFalse(try XCTUnwrap(gmail.accounts?.last).isActive)

        let noAuth = try XCTUnwrap(statuses.services["weather"])
        XCTAssertTrue(noAuth.connected)
        XCTAssertEqual(noAuth.accounts?.isEmpty, true)

        let pending = try XCTUnwrap(statuses.services["slack"])
        XCTAssertEqual(pending.pending, true)
        XCTAssertNil(pending.accounts)
    }

    func testAnUnreadableCredentialStoreIsNotAnEmptyInventory() throws {
        func statuses(_ json: String) throws -> ConnectorStatuses {
            try JSONDecoder().decode(ConnectorStatuses.self, from: Data(json.utf8))
        }

        // The one answer that withdraws its own authority: an empty map the
        // server explicitly labels as "we could not read the store".
        let unreadable = try statuses(#"{"configured":false,"credentialStore":"unavailable","services":{}}"#)
        XCTAssertTrue(unreadable.services.isEmpty)
        XCTAssertFalse(unreadable.isAuthoritative)

        // The three ways of still being authoritative. Each is asserted
        // separately because a rule that only recognised the case above would
        // pass a test that only checked the case above — and every one of
        // these would then start hiding accounts that really are gone.
        XCTAssertTrue(
            try statuses(#"{"configured":true,"credentialStore":"ok","services":{}}"#).isAuthoritative,
            "an empty list from a readable store really does mean nothing is connected"
        )
        XCTAssertTrue(
            try statuses(#"{"configured":true,"services":{}}"#).isAuthoritative,
            "a computer older than the field would otherwise have every answer treated as unknowable"
        )
        XCTAssertTrue(
            try statuses(#"{"configured":false,"credentialStore":"Unavailable","services":{}}"#).isAuthoritative,
            "only the exact string server/index.ts writes withdraws the claim; anything else is as unknown as an absent field"
        )
    }

    func testOneMalformedBotDoesNotHideTheRestOfTheFleet() throws {
        let json = """
        {
          "bots": [
            {"id":"broken","threadId":42},
            {
              "id":"good","threadId":"t1","name":"Scout","title":"","description":"",
              "notifications":true,"color":"green","unread":false,
              "modelSelection":{"instanceId":"i1","model":"m1"},"createdAt":1
            }
          ],
          "groups": []
        }
        """
        let fleet = try JSONDecoder().decode(Fleet.self, from: Data(json.utf8))
        XCTAssertEqual(fleet.bots.map(\.id), ["good"])
    }

    func testNeverDecodesProviderSessionCursors() throws {
        // resumeCursors is harness bookkeeping and must not be on the wire.
        // Asserted against the raw bytes, because a Swift type that simply
        // lacks the field would hide it.
        for name in ["bots-full", "bots-paged", "sse-frames"] {
            let raw = String(decoding: try fixture(name), as: UTF8.self)
            XCTAssertFalse(raw.contains("resumeCursors"), "\(name) carries provider session cursors")
        }
    }

    func testDecodesAThreadPage() throws {
        let page = try decode(ThreadPage.self, "thread-page")
        XCTAssertEqual(page.messages.count, 2)
        XCTAssertEqual(page.hasMore, true)
        // pages arrive oldest-first, which is what makes prepending correct
        let times = page.messages.map(\.at)
        XCTAssertEqual(times, times.sorted())
    }

    // MARK: - Messages and cards

    func testDecodesAnOptionsCard() throws {
        let message = try decode(Message.self, "options-card")
        XCTAssertEqual(message.kind, .options)
        XCTAssertEqual(message.role, .bot)
        let card = try XCTUnwrap(message.card)
        XCTAssertFalse(card.options.isEmpty)
        // the onboarding card has no request behind it, so it is history
        XCTAssertFalse(card.isPending)
        XCTAssertFalse(card.isPermission)
    }

    func testDecodesADirectCredentialRequestWithoutSenderMetadata() throws {
        let json = """
        {
          "id": "secret-1", "role": "bot", "kind": "secret", "at": 1786742413762,
          "text": "Complete this credential request securely on your computer.",
          "secret": {
            "target": "ttsKey", "label": "ElevenLabs API key",
            "description": "Enables text-to-speech voices in calls.",
            "placeholder": "Paste your ElevenLabs API key",
            "helpUrl": "https://elevenlabs.io/app/settings/api-keys",
            "requestKey": "request-key-1"
          }
        }
        """
        let message = try JSONDecoder().decode(Message.self, from: Data(json.utf8))

        XCTAssertEqual(message.kind, .secret)
        XCTAssertNil(message.from, "a direct chat gets its bot identity from the enclosing chat")
        XCTAssertEqual(message.secret?.target, "ttsKey")
        XCTAssertEqual(message.secret?.label, "ElevenLabs API key")
        XCTAssertEqual(message.secret?.requestKey, "request-key-1")
        XCTAssertTrue(try XCTUnwrap(message.secret).isPending)
        XCTAssertEqual(previewText(of: message), "ElevenLabs API key")
    }

    func testDecodesAChannelCredentialRequestWithItsSender() throws {
        let json = """
        {
          "id": "secret-2", "role": "bot", "kind": "secret", "at": 1786742413762,
          "from": {"botId": "bot-2", "name": "Robyn", "color": "purple"},
          "secret": {
            "target": "ttsKey", "label": "ElevenLabs API key",
            "description": "Enables voices.", "placeholder": "Paste key",
            "helpUrl": "https://elevenlabs.io/app/settings/api-keys",
            "requestKey": "request-key-2", "provided": true, "resumed": true
          }
        }
        """
        let message = try JSONDecoder().decode(Message.self, from: Data(json.utf8))

        XCTAssertEqual(message.kind, .secret)
        XCTAssertEqual(message.from?.botId, "bot-2")
        XCTAssertEqual(message.from?.name, "Robyn")
        XCTAssertFalse(try XCTUnwrap(message.secret).isPending)
        XCTAssertEqual(message.secret?.provided, true)
        XCTAssertEqual(message.secret?.resumed, true)
    }

    func testAPendingApprovalIsActionableAndAnAnsweredOneIsNot() throws {
        // The shape a live permission request takes, which the fixture rig
        // cannot produce without a real provider attached.
        let json = """
        {
          "id": "m1", "role": "bot", "kind": "options", "at": 1786742413762,
          "card": {
            "title": "Approval needed", "subtitle": "rm -rf ./build",
            "options": ["Allow", "Deny"], "requestId": "req-1",
            "tool": "Bash", "allowKey": "Bash:rm"
          }
        }
        """
        let card = try XCTUnwrap(try JSONDecoder().decode(Message.self, from: Data(json.utf8)).card)
        XCTAssertTrue(card.isPending)
        XCTAssertTrue(card.isPermission)
        XCTAssertEqual(card.allowKey, "Bash:rm")
        XCTAssertEqual(card.responseBehavior(for: "Allow"), "allow")
        XCTAssertEqual(card.responseBehavior(for: "Approve"), "allow")
        XCTAssertEqual(card.responseBehavior(for: "Yes"), "allow")
        XCTAssertEqual(card.responseBehavior(for: "Always allow"), "allow")
        XCTAssertEqual(card.responseBehavior(for: "Deny"), "deny")
        XCTAssertEqual(card.responseBehavior(for: " deny "), "deny")
        XCTAssertEqual(card.responseBehavior(for: "Cancel"), "deny")
        XCTAssertEqual(card.responseBehavior(for: "Dismiss"), "deny")
        XCTAssertTrue(card.shouldRememberPermission(for: "Always allow"))
        XCTAssertFalse(card.shouldRememberPermission(for: "Allow"))
        XCTAssertFalse(card.shouldRememberPermission(for: " deny "))

        var answered = card
        answered.answered = "Allow"
        XCTAssertFalse(answered.isPending, "an answered card must stop offering buttons")

        var dismissed = card
        dismissed.dismissed = true
        XCTAssertFalse(dismissed.isPending)
    }

    func testDecodesAReviewedSkillRequest() throws {
        let json = """
        {
          "id": "skill-card", "role": "bot", "kind": "options", "at": 1786742413762,
          "card": {
            "title": "Enable skill?", "subtitle": "Files expenses.",
            "options": ["Enable", "Deny"], "requestId": "req-skill", "tool": "stage_skill",
            "skillRequest": {
              "version": 1, "requestId": "req-skill", "botId": "bot-1", "threadId": "thread-1",
              "stagedId": "staged-1", "action": "create", "name": "file-expense",
              "gist": "Files expenses.", "source": "learn:conversation",
              "preview": "---\\nname: file-expense\\n---\\n", "sha256": "abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789", "warnings": [],
              "createdAt": 1786742413762
            }
          }
        }
        """
        let card = try XCTUnwrap(try JSONDecoder().decode(Message.self, from: Data(json.utf8)).card)
        XCTAssertEqual(card.skillRequest?.name, "file-expense")
        XCTAssertEqual(card.skillRequest?.source, "learn:conversation")
        XCTAssertEqual(card.skillRequest?.reviewedSha256, "abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789")
        XCTAssertEqual(card.responseBehavior(for: "Enable"), "allow")
        XCTAssertEqual(card.responseBehavior(for: "Deny"), "deny")
    }

    func testDecodesAReviewedSkillUpdate() throws {
        let json = """
        {
          "id": "skill-update", "role": "bot", "kind": "options", "at": 1786742413762,
          "card": {
            "title": "Update skill?", "subtitle": "Refreshes verification steps.",
            "options": ["Update", "Deny"], "requestId": "req-update", "tool": "stage_skill",
            "skillRequest": {
              "version": 1, "requestId": "req-update", "botId": "bot-1", "threadId": "thread-1",
              "stagedId": "staged-update", "action": "update", "name": "verify-app",
              "gist": "Refreshes verification steps.", "source": "learn:maintenance",
              "preview": "---\\nname: verify-app\\n---\\n", "sha256": "abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789", "warnings": [],
              "createdAt": 1786742413762
            }
          }
        }
        """
        let card = try XCTUnwrap(try JSONDecoder().decode(Message.self, from: Data(json.utf8)).card)
        XCTAssertEqual(card.skillRequest?.action, "update")
        XCTAssertEqual(card.responseBehavior(for: "Update"), "allow")
        XCTAssertEqual(card.responseBehavior(for: "Deny"), "deny")
    }

    func testOldSkillCardStillDecodesButCannotBeApproved() throws {
        let json = """
        {
          "id": "legacy-skill", "role": "bot", "kind": "options", "at": 1786742413762,
          "card": {
            "title": "Enable skill?", "subtitle": "Old proposal.",
            "options": ["Enable", "Dismiss"], "requestId": "req-old", "tool": "stage_skill",
            "skillRequest": {
              "version": 1, "requestId": "req-old", "botId": "bot-1", "threadId": "thread-1",
              "stagedId": "staged-old", "action": "create", "name": "old-skill",
              "gist": "Old proposal.", "warnings": [], "createdAt": 1786742413762
            }
          }
        }
        """
        let card = try XCTUnwrap(try JSONDecoder().decode(Message.self, from: Data(json.utf8)).card)
        XCTAssertEqual(card.skillRequest?.name, "old-skill")
        XCTAssertNil(card.skillRequest?.reviewedSha256)
        XCTAssertEqual(card.responseBehavior(for: "Dismiss"), "deny")
    }

    func testAQuestionSendsItsChoiceAsAnAnswer() throws {
        let message = try decode(Message.self, "options-card")
        let card = try XCTUnwrap(message.card)
        XCTAssertFalse(card.isPermission)
        XCTAssertEqual(card.responseBehavior(for: "Anything"), "answer")
        XCTAssertFalse(card.shouldRememberPermission(for: "Always allow"))
    }

    func testDecodesAMessageThatGainedAFieldWeDoNotKnow() throws {
        // The harness ships ahead of the app. An unknown key must not cost
        // the user their conversation.
        let json = """
        {"id":"m2","role":"user","kind":"text","at":1,"text":"hi","somethingNew":{"a":1}}
        """
        let message = try JSONDecoder().decode(Message.self, from: Data(json.utf8))
        XCTAssertEqual(message.text, "hi")
    }

    func testDecodesAThreadOpenedByABotAndOneOpenedByThePerson() throws {
        // Newer computers say which bot opened a thread on itself or a
        // teammate. The captured fixtures predate that, so every thread in
        // them was opened by the person — and must still decode as such.
        let json = """
        {"threadId":"t2","title":"Ship it","createdAt":1,
         "openedBy":{"botId":"scout","name":"Scout","delegationId":"d1","at":2}}
        """
        let opened = try JSONDecoder().decode(BotTask.self, from: Data(json.utf8))
        XCTAssertEqual(opened.openedBy?.botId, "scout")
        XCTAssertEqual(opened.openedBy?.name, "Scout")
        XCTAssertEqual(opened.openedBy?.delegationId, "d1")
        XCTAssertEqual(opened.openedBy?.at, 2)

        let minimal = try JSONDecoder().decode(
            BotTask.self,
            from: Data(#"{"threadId":"t1","title":"","createdAt":1,"openedBy":{"botId":"scout","name":"Scout","at":2}}"#.utf8)
        )
        XCTAssertNil(minimal.openedBy?.delegationId)

        let byThePerson = try JSONDecoder().decode(
            BotTask.self, from: Data(#"{"threadId":"t1","title":"","createdAt":1}"#.utf8)
        )
        XCTAssertNil(byThePerson.openedBy)
        for task in try decode(Fleet.self, "bots-paged").bots.flatMap({ $0.tasks ?? [] }) {
            XCTAssertNil(task.openedBy, task.threadId)
        }
    }

    func testDecodesAThreadABotClosedAndOneStillOpen() throws {
        // close_thread stamps who closed a thread; an open thread — and every
        // thread from an older computer — has no stamp and decodes as open.
        let closed = try JSONDecoder().decode(BotTask.self, from: Data("""
        {"threadId":"t2","title":"Ship it","createdAt":1,
         "openedBy":{"botId":"pm","name":"Parker","at":2},
         "closedBy":{"botId":"pm","name":"Parker","at":9}}
        """.utf8))
        XCTAssertEqual(closed.closedBy?.botId, "pm")
        XCTAssertEqual(closed.closedBy?.name, "Parker")
        XCTAssertEqual(closed.closedBy?.at, 9)
        XCTAssertTrue(closed.isClosed)
        XCTAssertEqual(closed.bylineLabel, "closed by Parker", "closed outranks opened on the one byline")

        let open = try JSONDecoder().decode(
            BotTask.self,
            from: Data(#"{"threadId":"t1","title":"","createdAt":1,"openedBy":{"botId":"pm","name":"Parker","at":2}}"#.utf8)
        )
        XCTAssertNil(open.closedBy)
        XCTAssertFalse(open.isClosed)
        XCTAssertEqual(open.bylineLabel, "opened by Parker")
        XCTAssertNil(try JSONDecoder().decode(BotTask.self, from: Data(#"{"threadId":"t1","title":"","createdAt":1}"#.utf8)).bylineLabel)
        for task in try decode(Fleet.self, "bots-paged").bots.flatMap({ $0.tasks ?? [] }) {
            XCTAssertFalse(task.isClosed, task.threadId)
        }
    }

    func testAThreadOpenedByABotSaysSoInTheList() throws {
        // Same words as the desktop's thread list, so a person reading both
        // screens reads one sentence.
        let opened = try JSONDecoder().decode(
            BotTask.self,
            from: Data(#"{"threadId":"t2","title":"Ship it","createdAt":1,"openedBy":{"botId":"scout","name":"Scout","at":2}}"#.utf8)
        )
        XCTAssertEqual(opened.openedByLabel, "opened by Scout")

        let byThePerson = try JSONDecoder().decode(
            BotTask.self, from: Data(#"{"threadId":"t1","title":"","createdAt":1}"#.utf8)
        )
        XCTAssertNil(byThePerson.openedByLabel)
    }

    func testDecodesAThreadRefOnAnActivityChipAndItsAbsence() throws {
        let json = """
        {"id":"m3","role":"bot","kind":"activity","at":1,
         "tool":{"name":"Opened thread #Ship it on Scout","ok":true},
         "threadRef":{"botId":"scout","threadId":"t2","title":"Ship it"}}
        """
        let chip = try JSONDecoder().decode(Message.self, from: Data(json.utf8))
        XCTAssertEqual(chip.kind, .activity)
        XCTAssertEqual(chip.tool?.name, "Opened thread #Ship it on Scout")
        XCTAssertEqual(chip.threadRef, ThreadRef(botId: "scout", threadId: "t2", title: "Ship it"))

        let receipt = try JSONDecoder().decode(
            Message.self,
            from: Data(#"{"id":"m4","role":"bot","kind":"activity","at":1,"tool":{"name":"Read","ok":true}}"#.utf8)
        )
        XCTAssertNil(receipt.threadRef)
        for message in try decode(ThreadPage.self, "thread-page").messages {
            XCTAssertNil(message.threadRef, message.id)
        }
    }

    // MARK: - Pairing and errors

    func testDecodesThePairResponse() throws {
        let paired = try decode(PairResponse.self, "pair-response")
        XCTAssertTrue(paired.token.hasPrefix("omb_"))
        XCTAssertEqual(paired.device.name, "Ada's iPhone")
        XCTAssertFalse(paired.serverName.isEmpty)
    }

    func testMalformedAdvisoryEndpointDoesNotDiscardAPairedToken() throws {
        let json = """
        {
          "token":"omb_device",
          "device":{"id":"d1","name":"Ada's iPhone","createdAt":1,"lastSeenAt":1},
          "serverName":"Ada's Mac",
          "hosts":["192.168.1.42"],
          "endpoints":[
            {"url":"https://mac.example","kind":"hosted","priority":0},
            {"url":"https://future.example","kind":"future-transport","priority":10},
            {"url":"http://192.168.1.42:8810","kind":"lan","priority":200}
          ]
        }
        """

        let paired = try JSONDecoder().decode(PairResponse.self, from: Data(json.utf8))

        XCTAssertEqual(paired.token, "omb_device")
        XCTAssertEqual(paired.hosts, ["192.168.1.42"])
        XCTAssertEqual(paired.endpoints?.map(\.kind), [.hosted, .lan])
    }

    func testDecodesTheHarnessErrorBodies() throws {
        // These are captured server contracts. Keep them verbatim until the
        // desktop changes in lockstep; the client passes them through.
        XCTAssertEqual(
            try decode(APIErrorBody.self, "unauthorized").error,
            "pair this device from Phone settings in OpenMausBot on your computer"
        )
        XCTAssertFalse(try decode(APIErrorBody.self, "forbidden").error.isEmpty)
        XCTAssertEqual(
            try decode(APIErrorBody.self, "pair-rejected").error,
            "no pairing is in progress — open Phone settings on your computer"
        )
    }

    func testDecodesInstancesAndConfig() throws {
        let instances = try decode(InstanceList.self, "instances").instances
        // Availability is a property of the machine that captured the
        // fixture, not of the wire contract. Pin the required identity and
        // catalog shape without making a developer's installed CLIs decide
        // whether this test passes.
        let instance = try XCTUnwrap(instances.first)
        XCTAssertFalse(instance.instanceId.isEmpty)
        XCTAssertFalse(instance.driverKind.isEmpty)

        let config = try decode(ConfigStatus.self, "config")
        XCTAssertEqual(config.profile?.name, "Ada Lovelace")
        XCTAssertEqual(config.box?.configured, false)
        // Captured bytes, not our idea of them: `describeVoice` always sends
        // the engine, so a sidecar that stopped forwarding it fails here
        // instead of quietly sending every built-in-voices user back to an
        // explanation about an ElevenLabs key. The captured value is stable on
        // any platform — the fabricated config selects no provider, so the
        // server's own fallback decides it.
        XCTAssertEqual(config.tts?.provider, "elevenlabs")
        XCTAssertEqual(config.voiceProvider, .elevenlabs)
    }

    // MARK: - Frames

    func testDecodesEveryCapturedFrame() throws {
        let frames = try decode([StreamFrame].self, "sse-frames")
        XCTAssertFalse(frames.isEmpty)

        var kinds: [String] = []
        for streamFrame in frames {
            switch streamFrame.frame {
            case let .hello(cursor, resumed):
                kinds.append("hello")
                XCTAssertTrue(cursor.contains(":"))
                XCTAssertFalse(resumed, "a cold connection has nothing to resume")
                XCTAssertNil(streamFrame.seq, "hello is not a replayable frame")
            case let .message(threadId, message):
                kinds.append("message")
                XCTAssertFalse(threadId.isEmpty)
                XCTAssertFalse(message.id.isEmpty)
                XCTAssertNotNil(streamFrame.seq)
            case let .bot(bot):
                kinds.append("bot")
                XCTAssertFalse(bot.id.isEmpty)
                XCTAssertNil(bot.messages, "bot frames carry no transcript")
            case let .unknown(kind):
                XCTFail("unhandled frame kind in fixtures: \(kind)")
            default:
                kinds.append("other")
            }
        }
        XCTAssertTrue(kinds.contains("hello"))
        XCTAssertTrue(kinds.contains("message"))
        XCTAssertTrue(kinds.contains("bot"))
    }

    func testAnUnknownFrameKindIsAbsorbedRatherThanThrown() throws {
        // the harness will add frame kinds; an old app must keep folding the
        // ones it knows instead of tearing down its stream
        let frame = try JSONDecoder().decode(
            StreamFrame.self,
            from: Data(#"{"kind":"routine.run","run":{"id":"r1"},"seq":9}"#.utf8)
        )
        XCTAssertEqual(frame.seq, 9)
        guard case let .unknown(kind) = frame.frame else {
            return XCTFail("expected .unknown, got \(frame.frame)")
        }
        XCTAssertEqual(kind, "routine.run")
    }

    func testDecodesANotifyFrame() throws {
        let json = """
        {"kind":"notify","seq":12,"notification":{
          "kind":"approval","botId":"b1","botName":"Scout","threadId":"t1",
          "title":"Scout needs approval","body":"rm -rf ./build"}}
        """
        let frame = try JSONDecoder().decode(StreamFrame.self, from: Data(json.utf8))
        guard case let .notify(notification) = frame.frame else {
            return XCTFail("expected .notify")
        }
        XCTAssertTrue(notification.isBlocking)
        XCTAssertEqual(notification.threadId, "t1")
        XCTAssertEqual(frame.frame.threadId, "t1")
    }

    // MARK: - A newer computer than the phone

    // The harness gains message kinds when it ships; the phone gains them
    // when the App Store gets round to it. So the phone talking to a newer
    // computer is the ordinary case, and it must survive one.

    func testAnUnknownMessageKindDecodes() throws {
        let json = """
        {"id":"m1","role":"bot","kind":"webhook","at":1,"text":"Stripe fired"}
        """
        let message = try JSONDecoder().decode(Message.self, from: Data(json.utf8))
        XCTAssertEqual(message.kind, .unknown)
        // and keeps what it can show
        XCTAssertEqual(message.text, "Stripe fired")
    }

    // A digest is known, not new: it must not take the unknown-kind path,
    // which draws any text it carries as a message bubble.
    func testADigestIsNotAnUnknownKind() throws {
        let json = """
        {"id":"m1","role":"bot","kind":"digest","at":1,"text":"[digest] · tools: shell ×1"}
        """
        let message = try JSONDecoder().decode(Message.self, from: Data(json.utf8))
        XCTAssertNotEqual(message.kind, .unknown)
    }

    func testACompactionMessageDecodesItsRecord() throws {
        let json = """
        {"id":"c1","role":"bot","kind":"compaction","at":1,"text":"[compaction] Earlier: …",
         "compaction":{"summary":"Earlier: the user asked for X.","firstKeptId":"c1","tokensBefore":12345,"by":"person"}}
        """
        let message = try JSONDecoder().decode(Message.self, from: Data(json.utf8))
        XCTAssertEqual(message.kind, .compaction)
        XCTAssertEqual(message.compaction?.summary, "Earlier: the user asked for X.")
        XCTAssertTrue(message.compaction?.chipText.hasPrefix("Context compacted · ") == true)
        XCTAssertTrue(message.compaction?.chipText.hasSuffix("345 tokens summarised") == true)
    }

    func testAnUnknownRoleIsNotAttributedToYou() throws {
        let json = """
        {"id":"m1","role":"system","kind":"text","at":1,"text":"hello"}
        """
        let message = try JSONDecoder().decode(Message.self, from: Data(json.utf8))
        XCTAssertEqual(message.role, .bot)
    }

    /// The one that matters. `kind` is not optional, so before this a single
    /// unrecognised message failed the decode of the entire response — the
    /// thread did not render one message oddly, it did not render.
    func testOneUnknownMessageDoesNotSinkThePage() throws {
        let json = """
        {"messages":[
          {"id":"m1","role":"user","kind":"text","at":1,"text":"go"},
          {"id":"m2","role":"bot","kind":"something-new","at":2,"text":"working"},
          {"id":"m3","role":"bot","kind":"text","at":3,"text":"done"}
        ],"hasMore":false}
        """
        let page = try JSONDecoder().decode(ThreadPage.self, from: Data(json.utf8))
        XCTAssertEqual(page.messages.count, 3)
        XCTAssertEqual(page.messages.map(\.kind), [.text, .unknown, .text])
        XCTAssertEqual(page.messages.map(\.id), ["m1", "m2", "m3"])
    }

    /// Same page, arriving one message at a time down the stream.
    func testAnUnknownMessageArrivesOverTheStream() throws {
        let json = """
        {"kind":"message","seq":3,"threadId":"t1",
         "message":{"id":"m9","role":"bot","kind":"routine.run","at":9,"text":"ran"}}
        """
        let frame = try JSONDecoder().decode(StreamFrame.self, from: Data(json.utf8))
        guard case let .message(threadId, message) = frame.frame else {
            return XCTFail("expected .message, got \(frame.frame)")
        }
        XCTAssertEqual(threadId, "t1")
        XCTAssertEqual(message.kind, .unknown)
        XCTAssertEqual(message.text, "ran")
    }
}
